name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: Automato/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
    - name: Test Project
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Debug --framework net5.0 --runtime win-x64 --self-contained true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.1
      with:
        name: automato-win-64
        path: ./Automato/bin/Debug/net5.0/win-x64/publish/
